---
title: "TP02"
output: html_document
date: "2025-01-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## EXERCICE 1

```{r }
mtcars
names(mtcars)
#ce sont toutes des valeurs quantitative mis a part vs am

length(unique(mtcars$mpg)) #mpg est une variable  continues
str(mtcars$cyl)
table(mtcars$mpg) #continues
table(mtcars$cyl) #discrete
table(mtcars$disp) #continue
table(mtcars$hp) #continue
table(mtcars$drat)#continue
table(mtcars$wt) #continue
table(mtcars$qsec)#continue
table(mtcars$carb)#discrete

summary(mtcars)

```


## Exercice 2



```{r }
mpg <- mtcars$mpg
disp <- mtcars$disp
boxplot(mpg,main = "mpg")
boxplot(disp,main = "disp")


```
```{r}
am <- mtcars$am
mpga <- mtcars[am == 0, "mpg"]
mpgm <- mtcars[am == 1, "mpg"]
boxplot(mpga,mpgm,names=c("automatique","manuelle"),main="mpg selon la transmission",col=c("blue","red"))

```

```{r}
am <- mtcars$am
table(am)
prop.table(am)

pie(table(am),main = "secteur")
barplot(table(am),main = "barre")
par(mfrow=c(1,2))

```

